export const greetings = [
  { language: "Japanese", greeting: "こんにちは" },
  { language: "English", greeting: "Hello!" },
  { language: "Korean", greeting: "안녕하세요" },
  { language: "Bulgarian", greeting: "Здравейте" },
  { language: "Spanish", greeting: "¡Hola!" },
  { language: "French", greeting: "Bonjour!" },
  { language: "Arabic", greeting: "مرحبا" },
  { language: "German", greeting: "Hallo!" },
  { language: "Chinese (Mandarin)", greeting: "你好!" },
  { language: "Italian", greeting: "Ciao!" },
  { language: "Portuguese", greeting: "Olá!" },
  { language: "Russian", greeting: "Привет!" },
  { language: "Bengali", greeting: "হ্যালো" },
  { language: "Croatian", greeting: "Bok!" },
  { language: "Czech", greeting: "Ahoj!" },
  { language: "Danish", greeting: "Hej!" },
  { language: "Dutch", greeting: "Hallo!" },
  { language: "Finnish", greeting: "Hei!" },
  { language: "Greek", greeting: "Γεια σας" },
  { language: "Hindi", greeting: "नमस्ते" },
  { language: "Hungarian", greeting: "Szia!" },
  { language: "Indonesian", greeting: "Halo!" },
  { language: "Latvian", greeting: "Sveiki!" },
  { language: "Lithuanian", greeting: "Sveiki!" },
  { language: "Norwegian", greeting: "Hei!" },
  { language: "Polish", greeting: "Cześć!" },
  { language: "Romanian", greeting: "Salut!" },
  { language: "Serbian", greeting: "Здраво" },
  { language: "Slovak", greeting: "Ahoj!" },
  { language: "Turkish", greeting: "Merhaba!" },
];
